# Generated by Django 3.1.6 on 2021-02-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='title_id',
        ),
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default=2, upload_to='poster/'),
            preserve_default=False,
        ),
    ]
