# Generated by Django 3.1.6 on 2021-02-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210217_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Movie_title',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
