# Generated by Django 3.1.6 on 2021-02-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210217_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='keywords',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
